import { app, BrowserWindow, ipcMain, Menu, session, shell } from 'electron';
import path from 'node:path';
import { autoUpdater } from 'electron-updater';
import { readFileSync, writeFileSync, renameSync, mkdirSync } from 'node:fs';

type ReceiptKind = 'ORDER' | 'MODIFICATION' | 'ADVANCE_CHEQUE' | 'CLOSE_CHEQUE' | 'DAY_BALANCE';
type Receipt = { kind: ReceiptKind; route?: ReceiptKind; language: 'ka' | 'en' | 'ru'; restaurantName: string; tableName: string; chequeNumber: number; orderId?: string; createdAt: string; items: readonly { name: string; quantity: number; unitPrice: number }[]; total: number; paymentMethod?: string; receivedAmount?: number; changeAmount?: number; details?: readonly string[]; labels: { title: string; table: string; cheque: string; total: string; payment?: string; received?: string; change?: string; } };
type PrinterBinding = { deviceName: string; paperWidthMm: number };
type Bindings = Partial<Record<ReceiptKind, PrinterBinding>>;
const DEFAULT_URL = 'https://meno.pandahouse2025.ge';
let startUrl = DEFAULT_URL; let mainWindow: BrowserWindow | null = null; let updateWindow: BrowserWindow | null = null; let allowedOrigins = new Set<string>();
function parseStartUrl(): string { const option = process.argv.find((value) => value.startsWith('--start-url=')); const candidate = option?.slice('--start-url='.length) || DEFAULT_URL; try { const url = new URL(candidate); if (!['https:', 'http:'].includes(url.protocol)) throw new Error('Unsupported'); return url.toString(); } catch { return DEFAULT_URL; } }
function bindingFile(): string { const directory = path.join(app.getPath('userData'), 'printing'); mkdirSync(directory, { recursive: true }); return path.join(directory, 'bindings.json'); }
function bindings(): Bindings { try { return JSON.parse(readFileSync(bindingFile(), 'utf8')) as Bindings; } catch { return {}; } }
function saveBindings(value: Bindings): void { const file = bindingFile(); const temporary = `${file}.tmp`; writeFileSync(temporary, JSON.stringify(value, null, 2), 'utf8'); renameSync(temporary, file); }
function senderAllowed(event: Electron.IpcMainInvokeEvent): boolean { try { return allowedOrigins.has(new URL(event.senderFrame?.url ?? '').origin); } catch { return false; } }
function escape(value: string): string { return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[character] ?? character); }
function receiptHtml(receipt: Receipt, widthMm: number): string {
  const isOrder = receipt.kind === 'ORDER';
  const rows = receipt.items.map((item) => isOrder
    ? `<li class="item order-item"><span>${escape(item.name)}</span><b>× ${item.quantity}</b></li>`
    : `<div class="item"><span>${escape(item.name)}<small>${item.quantity} × ${item.unitPrice.toFixed(2)}</small></span><b>${(item.quantity * item.unitPrice).toFixed(2)}</b></div>`).join('');
  const details = receipt.details?.length ? `<section class="details">${receipt.details.map((detail) => `<p>${escape(detail)}</p>`).join('')}</section>` : '';
  const brand = receipt.kind === 'ADVANCE_CHEQUE' ? `<div class="brand">● ${escape(receipt.restaurantName)}<small>POS</small></div>` : '';
  const total = isOrder ? '' : `<div class="dash"></div><div class="total"><span>${escape(receipt.labels.total)}</span><strong>${receipt.total.toFixed(2)}</strong></div>`;
  const itemMarkup = isOrder ? `<ul class="order-items">${rows}</ul>` : `<section class="receipt-items">${rows}</section>`;
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escape(receipt.labels.title)}</title><style>@page{size:${widthMm}mm auto;margin:0}*{box-sizing:border-box}html,body{margin:0;background:#fff;color:#000;font:11px/1.3 Arial,sans-serif}.receipt{width:${widthMm}mm;padding:3mm 4mm}.brand{display:grid;place-items:center;margin:0 0 3mm;font-size:17px;font-weight:700;letter-spacing:1px}.brand small{font-size:10px;letter-spacing:3px}h1{margin:0 0 3mm;text-align:center;font-size:15px}.meta{text-align:center;margin:0}.dash{margin:3mm 0;border-top:1px dashed #000}.item,.total{display:flex;justify-content:space-between;gap:4mm}.item{margin:0 0 2mm}.item span{font-weight:700}.item small{display:block;font-weight:400}.order-items{margin:0;padding-left:4mm}.order-item{padding-left:1mm}.details{margin-top:3mm;padding:2mm;border:1px solid #000}.details p{margin:0 0 1.5mm}.details p:last-child{margin-bottom:0}.total{font-size:15px;font-weight:800}.payment{display:grid;grid-template-columns:1fr auto;gap:2mm 5mm;margin-top:3mm}footer{margin-top:4mm;text-align:center;font-size:10px}</style></head><body><main class="receipt">${brand}<h1>${escape(receipt.labels.title)}</h1><p class="meta">${escape(receipt.labels.table)}: ${escape(receipt.tableName)}<br>${escape(receipt.labels.cheque)} #${receipt.chequeNumber.toString().padStart(6, '0')}${receipt.orderId ? `<br>${escape(receipt.orderId)}` : ''} · ${escape(receipt.createdAt)}</p><div class="dash"></div>${itemMarkup}${details}${total}${receipt.paymentMethod ? `<div class="payment"><span>${escape(receipt.labels.payment ?? '')}</span><b>${escape(receipt.paymentMethod)}</b>${receipt.receivedAmount !== undefined ? `<span>${escape(receipt.labels.received ?? '')}</span><b>${receipt.receivedAmount.toFixed(2)}</b>` : ''}${receipt.changeAmount !== undefined ? `<span>${escape(receipt.labels.change ?? '')}</span><b>${receipt.changeAmount.toFixed(2)}</b>` : ''}</div>` : ''}<footer>${escape(receipt.restaurantName)}</footer></main></body></html>`;
}
async function printReceipt(receipt: Receipt): Promise<{ ok: boolean; message?: string }> { const binding = bindings()[receipt.route ?? receipt.kind]; const printWindow = new BrowserWindow({ show: false, webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false } }); try { const widthMm = Math.min(100, Math.max(40, binding?.paperWidthMm ?? 80)); await printWindow.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(receiptHtml(receipt, widthMm))}`); const contentHeightPx = await printWindow.webContents.executeJavaScript(`Math.ceil(document.querySelector('.receipt')?.getBoundingClientRect().height ?? 0)`); const pageHeightMm = Math.min(1000, Math.max(25, Math.ceil(Number(contentHeightPx) * 25.4 / 96 + 1))); const result = await new Promise<boolean>((resolve) => printWindow.webContents.print({ silent: true, printBackground: true, deviceName: binding?.deviceName || undefined, pageSize: { width: Math.round(widthMm * 1000), height: Math.round(pageHeightMm * 1000) } }, (success) => resolve(success))); return result ? { ok: true } : { ok: false, message: 'Windows could not submit the receipt to the selected printer.' }; } catch (error) { return { ok: false, message: error instanceof Error ? error.message : 'Print failed.' }; } finally { if (!printWindow.isDestroyed()) printWindow.destroy(); } }
function updateScreen(message: string, progress = 15): void { if (!updateWindow || updateWindow.isDestroyed()) return; const script = `document.getElementById('message').textContent=${JSON.stringify(message)};document.getElementById('fill').style.width='${Math.max(8, Math.min(100, progress))}%';`; void updateWindow.webContents.executeJavaScript(script); }
function createUpdateWindow(): void { updateWindow = new BrowserWindow({ width: 460, height: 220, show: true, resizable: false, frame: false, alwaysOnTop: true, backgroundColor: '#13251d', webPreferences: { contextIsolation: true, nodeIntegration: false, sandbox: true } }); void updateWindow.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent('<!doctype html><style>body{margin:0;display:grid;place-items:center;height:100vh;background:#13251d;color:#fff;font:16px Arial}.card{width:320px;text-align:center}.logo{font-weight:800;letter-spacing:2px}.bar{height:8px;border-radius:9px;background:#33483d;overflow:hidden;margin-top:22px}.fill{height:100%;width:12%;background:#829549;transition:width .2s}</style><main class="card"><div class="logo">MENO POS</div><p id="message">Checking for updates…</p><div class="bar"><div class="fill" id="fill"></div></div></main>')}`); }
async function updateBeforeStart(): Promise<boolean> { if (!app.isPackaged) return true; createUpdateWindow(); autoUpdater.autoDownload = false; autoUpdater.autoInstallOnAppQuit = true; return new Promise((resolve) => { let starting = false; const startWithoutUpdate = () => { if (starting) return; starting = true; setTimeout(() => { updateWindow?.close(); resolve(true); }, 350); }; autoUpdater.once('checking-for-update', () => updateScreen('Checking for updates…', 15)); autoUpdater.once('update-available', async () => { updateScreen('Downloading the latest Meno POS…', 25); try { await autoUpdater.downloadUpdate(); } catch { startWithoutUpdate(); } }); autoUpdater.on('download-progress', (progress) => updateScreen(`Downloading update… ${Math.round(progress.percent)}%`, progress.percent)); autoUpdater.once('update-downloaded', () => { updateScreen('Update ready. Restarting Meno POS…', 100); setTimeout(() => autoUpdater.quitAndInstall(), 450); }); autoUpdater.once('update-not-available', startWithoutUpdate); autoUpdater.once('error', startWithoutUpdate); void autoUpdater.checkForUpdates().catch(startWithoutUpdate); }); }function toggleMenuBar(): void { if (!mainWindow) return; const visible = !mainWindow.isMenuBarVisible(); mainWindow.setMenuBarVisibility(visible); mainWindow.setAutoHideMenuBar(!visible); }
function configureApplicationMenu(): void { Menu.setApplicationMenu(Menu.buildFromTemplate([{ label: 'Meno POS', submenu: [{ label: 'Show / hide menu', accelerator: 'Ctrl+Shift+M', click: toggleMenuBar }, { type: 'separator' }, { role: 'quit', label: 'Exit' }] }, { label: 'Developer', submenu: [{ label: 'Inspect element', accelerator: 'Ctrl+Shift+I', click: () => mainWindow?.webContents.openDevTools({ mode: 'detach' }) }] }])); }function createMainWindow(): void { mainWindow = new BrowserWindow({ width: 1440, height: 900, minWidth: 900, minHeight: 650, show: false, backgroundColor: '#0f1d17', webPreferences: { preload: path.join(__dirname, 'preload.js'), contextIsolation: true, nodeIntegration: false, sandbox: true } }); mainWindow.once('ready-to-show', () => { mainWindow?.setAutoHideMenuBar(true); mainWindow?.setMenuBarVisibility(false); mainWindow?.show(); }); mainWindow.webContents.on('before-input-event', (event, input) => { if (input.type === 'keyDown' && input.key === 'F10') { event.preventDefault(); toggleMenuBar(); } }); void mainWindow.loadURL(startUrl); mainWindow.webContents.setWindowOpenHandler(({ url }) => { void shell.openExternal(url); return { action: 'deny' }; }); }
app.whenReady().then(async () => { startUrl = parseStartUrl(); allowedOrigins = new Set([new URL(DEFAULT_URL).origin, new URL(startUrl).origin]); session.defaultSession.setPermissionRequestHandler((_webContents, _permission, callback) => callback(false)); ipcMain.handle('desktop:printers', async (event) => senderAllowed(event) ? mainWindow?.webContents.getPrintersAsync() ?? [] : []); ipcMain.handle('desktop:bindings:get', (event) => senderAllowed(event) ? bindings() : {}); ipcMain.handle('desktop:bindings:save', (event, kind: ReceiptKind, value: PrinterBinding) => { if (!senderAllowed(event) || !['ORDER', 'MODIFICATION', 'ADVANCE_CHEQUE', 'CLOSE_CHEQUE', 'DAY_BALANCE'].includes(kind)) return false; const stored = bindings(); if (!value?.deviceName) delete stored[kind]; else stored[kind] = { deviceName: value.deviceName, paperWidthMm: Math.min(100, Math.max(40, Number(value.paperWidthMm) || 80)) }; saveBindings(stored); return stored; }); ipcMain.handle('desktop:print', (event, receipt: Receipt) => senderAllowed(event) ? printReceipt(receipt) : { ok: false, message: 'This page is not allowed to print.' }); if (await updateBeforeStart()) createMainWindow(); configureApplicationMenu(); app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createMainWindow(); }); });
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });



